// Single source of truth for all Monday column IDs used across Jarvis.
// Generated by Session 2 setup scripts:
//   setup/create-activity-log-board.js
//   setup/create-management-leads-columns.js

export const MANAGEMENT_LEADS_BOARD = '5891626711'

export const ACTIVITY_LOG_BOARD = '18414226069'

export const MANAGEMENT_LEADS_COLUMNS = {
  // Existing columns
  status:               'status5',
  leadProfile:          'text_mm1x8cgy',
  presentationResponse: 'long_text_mm2pse8d',
  callRecording:        'file_mm1daxvv',
  specialOffer:         'dropdown_mm0wabga',
  offerExpiry:          'date_mm0wdvyx',
  estAirbnbRent:        'numbers_mkn25e0y',
  address:              'text6',
  email:                'text_mkygb5xx',
  phoneE164:            'phone_mm1hp0a8',

  // New columns from Phase 2
  dateFirstQualified:   'date_mm3jkn8w',
  dateBecameCustomer:   'date_mm3j751s',
  emailsSent:           'numeric_mm3j6wj9',
  wasNoShowed:          'boolean_mm3jwt5e',
  waStatus:             'color_mm3j9rd4',
  waFirstSent:          'date_mm3jbstp',
  waLastReply:          'date_mm3jzdca',
  waMessagesSent:       'numeric_mm3jrh70',
  waReplies:            'numeric_mm3j1dff',
  waTemplateUsed:       'text_mm3jr05s',
  waConversation:       'long_text_mm3jj9fg',
  waCompleted:          'boolean_mm3jfr4g',
} as const

export const ACTIVITY_LOG_COLUMNS = {
  leadName:   'text_mm3j7z80',
  leadId:     'numeric_mm3j8j6h',
  eventType:  'dropdown_mm3jq119',
  from:       'text_mm3j2tdt',
  to:         'text_mm3jrxk9',
  timestamp:  'date_mm3j7b8n',
  source:     'dropdown_mm3jrcq9',
  notes:      'long_text_mm3jh46',
} as const
